# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_link',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
