# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_video_link_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_link',
            name='url_link',
        ),
        migrations.AddField(
            model_name='video_link',
            name='videoId',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
