# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20161117_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to=b''),
        ),
    ]
